### ISSUE TITLE
Updating manually my MPC X

### ISSUE THREAD

**Issue by TheKikGen** [TheKikGen/MPC-LiveXplore#17]
(Original post From JuJulien94) Thank you for your site it s really helpful. But I have a situation... It s seems that my mpc x is only detected by computers in controller mode but never in normal or update mode which prevents me from any update, therefore I'm stuck on 2.0.7 for ever it seems. I connected to the console via uart USB and I can log in and see what s going on but that s about it. My question to you the kik is is it possible to flash through the console with uart or is it only possible th(fromrough "regular" USB? And What should I do to fix the issue. I was thinking reinstalling factory content but I don't have it and I m unsure if it would the trick of replacing a missing driver file(?). 
I m about to give up after a few months but I felt I had to ask a specialist before lol. 
Regards

**Comment by henning** [comment]
Disclaimer: 
I dont wanna be a jerk about this, but try to help to identify the problem and what kind of action could result from this issue!

So: What should be done about this?

Sounds partially rather like a support question that should go towards akai themselves if there are generic problems to get updated images onto the device and recognize it on some not further described computers. 

At least some info about the OS where this is observed and if even updating via SD Card isn't working / is no option.

also, what does "i dont have the factory content" mean? It can be downloaded from akai.

The question that might be easily answered by someone with more MPC hacking experience is "My question to you the kik is is it possible to flash through the console with uart " - that sounds like a relatively  simple yes/no/I never tried but its likely/unlikely
