### ISSUE TITLE
Midi over Ethernet question

### ISSUE THREAD

**Issue by johnsq** [TheKikGen/MPC-LiveXplore#22]
First, please let me applaud your work here.  If I had not discovered MPC-LiveXplore, I would have sent my MPC Live II back. I take offence of being locked out of Global Midi by the manufacturer I handed my cash to. Not cool AKAI :(.

Anyway, I was wondering if you knew of a config change that would enable my MPC Live II to work with standard RTMidi protocols. Currently, as I'm sure you are aware, network midi is locked down to their own 'Akai Professional Network Midi' application, which runs only on Mac and Windows. If it were possible to turn off whatever authentication they use, I could happily connect network midi to my iPad.

Thanks

**Comment by TheKikGen** [comment]
It's on my list....check another post here , and a solution built by David Moreno.
https://github.com/TheKikGen/MPC-LiveXplore/issues/19

Il will include that in a bootstrap module....when I'll have time :-) !

You can try to do that your self.  David has posted a zip file containing his rtpmidi hack.

**Comment by TheKikGen** [comment]
Yes. I'm currently uploading somes updates of firmwares images.  Small adjustment but long uploads...

**Comment by johnsq** [comment]
Thanks for your help @TheKikGen :)

**Comment by TheKikGen** [comment]
rtpmidi is currently running on my mpc live...
