### ISSUE TITLE
asset files needs a bit fixing / reoganizing

### ISSUE THREAD

**Issue by egandro** [TheKikGen/MPC-LiveXplore#28]
Can you please fix the zip files? I will need them for the custom firmware builder :) 

The following files exists in the custom firmware, but not in the **TKGL_Arp Patterns.zip** file.

```
/usr/share/Akai/SME0/Arp Patterns/999-zz-Melodic-Arp-5-Beats.mid
/usr/share/Akai/SME0/Arp Patterns/999-zz-Melodic-Chords-6-Beats.mid
/usr/share/Akai/SME0/Arp Patterns/999-zz-Melodic-Five-Pattern-1.mid
/usr/share/Akai/SME0/Arp Patterns/999-zz-Melodic-Five-Pattern-2.mid
/usr/share/Akai/SME0/Arp Patterns/999-zz-Melodic-Jarre Of Hearts.mid
/usr/share/Akai/SME0/Arp Patterns/999-zz-Melodic-Major-b6-01.mid
/usr/share/Akai/SME0/Arp Patterns/999-zz-Melodic-Major-b6-02.mid
/usr/share/Akai/SME0/Arp Patterns/999-zz-Melodic-Minor-b6-01.mid
/usr/share/Akai/SME0/Arp Patterns/999-zz-Melodic-Minor-b6-02.mid
/usr/share/Akai/SME0/Arp Patterns/999-zz-Melodic-Minor-b6-03.mid
/usr/share/Akai/SME0/Arp Patterns/999-zz-Melodic-Minor-b6-04.mid
/usr/share/Akai/SME0/Arp Patterns/999-zz-Melodic-Piano Riff.mid
/usr/share/Akai/SME0/Arp Patterns/999-zz-Melodic-Seven-Pattern.mid
```

The following files exist in **TKGL_FX Racks TKGL.zip** but not on the custom firmware.

```
FX Racks/07 Performance/Crossover Phaser Break.xfx
FX Racks/07 Performance/Crossover Phasor Delay.xfx
FX Racks/07 Performance/DJ Comb.xfx
FX Racks/07 Performance/DJ Master Channel.xfx
FX Racks/07 Performance/Filter Gate.xfx
FX Racks/07 Performance/Flanged Filter.xfx
FX Racks/07 Performance/Groovemaker Pad.xfx
FX Racks/07 Performance/Infinity.xfx
FX Racks/07 Performance/Its Alive.xfx
FX Racks/07 Performance/Mouth Percussion.xfx
FX Racks/07 Performance/Moving LoFi.xfx
FX Racks/07 Performance/Repeat Stop Delay.xfx
FX Racks/07 Performance/Repeat Stop Washout.xfx
FX Racks/07 Performance/Space Delay.xfx
FX Racks/07 Performance/Sweeper.xfx
```

The directory structure of "FX Racks" is reorganized. This is from Firmware 2.10.1 that is different from **TKGL_FX Racks TKGL.zip**.

```
$ e2ls -l "out/rootfs_vanilla.img:/usr/share/Akai/SME0/FX Racks/"
   5752   40755     0     0     1024 19-Jul-2021 17:00 01 Drums and Percussion
   5765   40755     0     0     1024 19-Jul-2021 17:00 02 Voice
   5781   40755     0     0     1024 19-Jul-2021 17:00 03 Guitar
   5785   40755     0     0     1024 19-Jul-2021 17:00 04 Bass
   5789   40755     0     0     1024 19-Jul-2021 17:00 05 Keyboard
   5792   40755     0     0     1024 19-Jul-2021 17:00 06 Synth
   5797   40755     0     0     1024 19-Jul-2021 17:00 07 Experimental
   5808   40755     0     0     1024 19-Jul-2021 17:00 08 LoFi
   5814   40755     0     0     1024 19-Jul-2021 17:00 09 FXReturn
   5821   40755     0     0     1024 19-Jul-2021 17:00 10 Mastering
   5825   40755     0     0     1024 19-Jul-2021 17:00 11 Sampling
```

**Comment by TheKikGen** [comment]
I'm wondering about to move bonus Arp patterns / fx Racks outside the image (on sdcard), and let the img original.
I will implement that in the bootstrap, with an overlay as I already did, so don't spend too much time on this.

**Comment by egandro** [comment]
> I'm wondering about to move bonus Arp patterns / fx Racks outside the image (on sdcard), and let the img original. I will implement that in the bootstrap, with an overlay as I already did, so don't spend too much time on this.

Well you can't fix this if it's dead :)

This is the script how my cfw builder does the installation. It simply unzips the zip file and copies the folders.

https://github.com/egandro/MPC-LiveXplore/blob/cfw-builder/cfw-builder/steps/install-fx-racks.sh

If they number increased - something is fishy. I print a warning.

As AKAI might change stuff like this in their manner, we can't fix it.

What you can do, remove the numbers from the items in the ZIP file and I find the folders in the firmware.
