### ISSUE TITLE
Jack2

### ISSUE THREAD

**Issue by velolala** [TheKikGen/MPC-LiveXplore#38]
Hey!
I’m excited and scared that I found this repository…
Have you ever considered launching a jack server on a MPC?
I wonder if that could be abused to work around some of the MIDI routing issues we see in the current firmware. E.g. the Note Off bug and the problems with the filtering.
I have not gotten my hands dirty yet, so all I’m hoping for is someone, who has already wasted time on this, telling me, that it can’t be done for reasons XYZ. Otherwise I’m afraid I’ll have to go down a rabbit hole rather than making music :-o

**Comment by TheKikGen** [comment]
Yes . I tried Jack2 and ran it succefully on my MPC Live months ago.  But the MPC software uses only Alsa.
About the horrible midi note off bug,  it is an internal midi bug, I mean in the application code itself.
