### ISSUE TITLE
Sequence change

### ISSUE THREAD

**Issue by ShoveD01** [TheKikGen/MPC-LiveXplore#39]
Hi did I once read that when ssh enabled, and a sequence was changed via a midi controller, it didn't start the new sequence from the start, rather it started the new sequence from the position that it left the previous sequence.?

**Comment by ShoveD01** [comment]
How is it done then?

**Comment by arcin** [comment]
SSH is just a tool that gives you access to the filesystem over a network. Anything beyond that (ex: using the mpc hardware, external midi controllers, akai software) isn't related to SSH.
