### ISSUE TITLE
MPC 2.11.1 update

### ISSUE THREAD

**Issue by IrregularShed** [TheKikGen/MPC-LiveXplore#40]
Hi everyone

The new OS is out and I'd like to have it SSH enabled so that I can do file handling on my PC, but having opened the update.img inside the update application I've realised how out of my depth I am!

Is there likely to be a pre-patched image in the near future?

Thanks for everything!

**Comment by TheKikGen** [comment]
I will upload a new patched img on next saturday.  Image already done and patched, ready to be uploaded.

**Comment by LoopinLab** [comment]
Unfortunately, AKAI has introduced a nasty bug in 2.11.2 that stops the Looper whenever you change to another view (such as the Track Mute Screen). It seems they fixed it in 2.11.4 

This pretty much ruins our Live performance. Before moving back to 2.10.1 - can you tell me if there's a chance that you develop an SSH version of 2.11.4 or 2.11.5 anytime soon? That would be awesome. 

All the Best, Michael.

**Comment by TheKikGen** [comment]
Yes.  It is exactly the same for the last 2.11.5 with MP3.  Not usable anymore.  I'll wait for a  more stable version.
2.11.6 ???

**Comment by LoopinLab** [comment]
2.11.6 is out. But no release notes about bugfixes. 🙄

**Comment by TheKikGen** [comment]
2.11.6 patched with SSH mod and available on the home page here...

**Comment by LoopinLab** [comment]
Awesome! I already installed it and it looks good. The Looper works again! Thank you very much!
