### ISSUE TITLE
The Fabric Collection

### ISSUE THREAD

**Issue by MaxPowerz** [TheKikGen/MPC-LiveXplore#44]
Just wanted to let you know the Fabric collection are not individual plugins.
The main Fabric plugin is required for the other 3 to work (XL, Piano, Electric Piano).
Maybe it would be better to merge all 4 zips into a single zip as to avoid confusion.

**Comment by TheKikGen** [comment]
Thanks for that information.  I will add a notice to the post, as i will not manage zip pakages on my side.
