### ISSUE TITLE
MPC One +

### ISSUE THREAD

**Issue by TheWhiteHatter** [TheKikGen/MPC-LiveXplore#54]
Due to slight hardware differences between the MPC One and the One Plus: 
1.) The removal of physical ethernet port.
2.) Addition of on-board WiFi and Bluetooth.
3.) Change of on-board storage from 4gb to 16gb.
should I be concerned about flashing my One +, with the currently supplied images?

Thank you, for what you do!! :)

**Comment by TheKikGen** [comment]
Hi.  Core hardware is the same.   The supplied image will unlock SSH so you have access to the internal system of your MPC.
The firmware it self is not modified at all.

**Comment by TheWhiteHatter** [comment]
Thank you! ( ^_-) v

**Comment by TheWhiteHatter** [comment]
Thank you! ( ^_-) v
